# Generated by Django 5.0.14 on 2026-07-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["barcode"], name="product_var_barcode_9fdfa1_idx"
            ),
        ),
    ]
