# Generated by Django 5.0.14 on 2026-07-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0004_partition_inventory_movements"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="resulting_balance",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
