# Generated by Django 5.0.14 on 2026-08-02 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0005_inventorymovement_resulting_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="inventario.warehouse",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RECEIVED", "RECEIVED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
