# Generated by Django 5.0.14 on 2026-08-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventario",
            "0006_purchaseorder_received_at_purchaseorder_warehouse_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="concept",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "PURCHASE"),
                    ("SALE", "SALE"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("RETURN", "RETURN"),
                    ("TRANSFER_OUT", "TRANSFER_OUT"),
                    ("TRANSFER_IN", "TRANSFER_IN"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VolumePricingTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="inventario.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "volume_pricing_tiers",
            },
        ),
        migrations.AddConstraint(
            model_name="volumepricingtier",
            constraint=models.UniqueConstraint(
                fields=("variant", "min_quantity"), name="uq_volume_pricing_tier"
            ),
        ),
    ]
