# Generated by Django 5.0.14 on 2026-08-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0004_role_deleted_at_role_deleted_by"),
        ("ventas", "0005_quote_quotedetail_productreservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "MONTHLY"),
                            ("QUARTERLY", "QUARTERLY"),
                            ("YEARLY", "YEARLY"),
                        ],
                        max_length=10,
                    ),
                ),
                ("benefits", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "membership_plans",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("FROZEN", "FROZEN"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("frozen_since", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="ventas.customer",
                    ),
                ),
            ],
            options={
                "db_table": "memberships",
            },
        ),
        migrations.CreateModel(
            name="MembershipPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[("CASH", "CASH"), ("CARD", "CARD"), ("YAPE", "YAPE")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="gimnasio.membership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_payments",
                        to="usuarios.user",
                    ),
                ),
            ],
            options={
                "db_table": "membership_payments",
            },
        ),
        migrations.AddConstraint(
            model_name="membershipplan",
            constraint=models.CheckConstraint(
                check=models.Q(("periodicity__in", ["MONTHLY", "QUARTERLY", "YEARLY"])),
                name="ck_membership_plans_periodicity",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="gimnasio.membershipplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershippayment",
            constraint=models.CheckConstraint(
                check=models.Q(("method__in", ["CASH", "CARD", "YAPE"])),
                name="ck_membership_payments_method",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["status", "end_date"], name="memberships_status_fe4c2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["ACTIVE", "FROZEN", "EXPIRED", "CANCELLED"])
                ),
                name="ck_memberships_status",
            ),
        ),
    ]
