# Generated by Django 5.0.14 on 2026-08-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gimnasio", "0001_initial"),
        ("usuarios", "0004_role_deleted_at_role_deleted_by"),
        ("ventas", "0005_quote_quotedetail_productreservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("max_capacity", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gym_classes",
                        to="usuarios.employee",
                    ),
                ),
            ],
            options={
                "db_table": "gym_classes",
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "MONDAY"),
                            ("TUESDAY", "TUESDAY"),
                            ("WEDNESDAY", "WEDNESDAY"),
                            ("THURSDAY", "THURSDAY"),
                            ("FRIDAY", "FRIDAY"),
                            ("SATURDAY", "SATURDAY"),
                            ("SUNDAY", "SUNDAY"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gym_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="gimnasio.gymclass",
                    ),
                ),
            ],
            options={
                "db_table": "class_schedules",
            },
        ),
        migrations.CreateModel(
            name="ClassBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVADO", "RESERVADO"),
                            ("ASISTIO", "ASISTIO"),
                            ("NO_ASISTIO", "NO_ASISTIO"),
                            ("CANCELADO", "CANCELADO"),
                        ],
                        default="RESERVADO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_bookings",
                        to="ventas.customer",
                    ),
                ),
                (
                    "gym_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="gimnasio.gymclass",
                    ),
                ),
            ],
            options={
                "db_table": "class_bookings",
            },
        ),
        migrations.CreateModel(
            name="MembershipGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "holder_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_groups_held",
                        to="ventas.customer",
                    ),
                ),
            ],
            options={
                "db_table": "membership_groups",
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="gimnasio.membershipgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="classschedule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "day_of_week__in",
                        [
                            "MONDAY",
                            "TUESDAY",
                            "WEDNESDAY",
                            "THURSDAY",
                            "FRIDAY",
                            "SATURDAY",
                            "SUNDAY",
                        ],
                    )
                ),
                name="ck_class_schedules_day",
            ),
        ),
        migrations.AddIndex(
            model_name="classbooking",
            index=models.Index(
                fields=["gym_class", "class_date", "status"],
                name="class_booki_gym_cla_c18dad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classbooking",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["RESERVADO", "ASISTIO", "NO_ASISTIO", "CANCELADO"])
                ),
                name="ck_class_bookings_status",
            ),
        ),
    ]
