# Generated by Django 5.2.17 on 2026-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gimnasio",
            "0002_gymclass_classschedule_classbooking_membershipgroup_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershippayment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
