# Generated by Django 5.0.14 on 2026-07-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_plan_platformstaff_subscription_subscriptionpayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
