# Generated by Django 5.0.14 on 2026-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_platformauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
