# Generated by Django 5.0.14 on 2026-08-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_tenant_canceled_at_tenant_provisioning_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantFeatureOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_code",
                    models.CharField(
                        choices=[
                            ("HAS_SALES_MODULE", "HAS_SALES_MODULE"),
                            ("HAS_PURCHASES_MODULE", "HAS_PURCHASES_MODULE"),
                            ("HAS_VARIANTS", "HAS_VARIANTS"),
                            ("HAS_MULTI_WAREHOUSE", "HAS_MULTI_WAREHOUSE"),
                            ("HAS_HR_MODULE", "HAS_HR_MODULE"),
                            ("HAS_CASH_MODULE", "HAS_CASH_MODULE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_overrides",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_feature_overrides",
            },
        ),
        migrations.CreateModel(
            name="TenantImpersonationSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "platform_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonation_sessions",
                        to="core.platformstaff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonation_sessions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_impersonation_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantfeatureoverride",
            constraint=models.UniqueConstraint(
                fields=("tenant", "feature_code"), name="uq_tenant_feature_override"
            ),
        ),
    ]
