# Generated by Django 5.0.14 on 2026-08-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_tenantfeatureoverride_tenantimpersonationsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionDiscount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "override_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reason", models.TextField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="core.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_notes",
                        to="core.platformstaff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="subscriptiondiscount",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("discount_percent__isnull", False),
                        ("override_price__isnull", True),
                    ),
                    models.Q(
                        ("discount_percent__isnull", True),
                        ("override_price__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_subscription_discount_exactly_one_type",
            ),
        ),
    ]
