# Generated by Django 5.0.14 on 2026-08-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_subscriptiondiscount_tenantnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="cash_difference_alert_threshold",
            field=models.DecimalField(decimal_places=4, default=20, max_digits=12),
        ),
    ]
