# Generated by Django 5.0.14 on 2026-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_sales_void_return_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="dashboard_refresh_minutes",
            field=models.IntegerField(default=15),
        ),
    ]
