# Generated by Django 5.0.14 on 2026-08-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_tenantsettings_dashboard_refresh_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="gym_module_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="planfeature",
            name="feature_code",
            field=models.CharField(
                choices=[
                    ("HAS_SALES_MODULE", "HAS_SALES_MODULE"),
                    ("HAS_PURCHASES_MODULE", "HAS_PURCHASES_MODULE"),
                    ("HAS_VARIANTS", "HAS_VARIANTS"),
                    ("HAS_MULTI_WAREHOUSE", "HAS_MULTI_WAREHOUSE"),
                    ("HAS_HR_MODULE", "HAS_HR_MODULE"),
                    ("HAS_CASH_MODULE", "HAS_CASH_MODULE"),
                    ("HAS_GYM_MODULE", "HAS_GYM_MODULE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenantfeatureoverride",
            name="feature_code",
            field=models.CharField(
                choices=[
                    ("HAS_SALES_MODULE", "HAS_SALES_MODULE"),
                    ("HAS_PURCHASES_MODULE", "HAS_PURCHASES_MODULE"),
                    ("HAS_VARIANTS", "HAS_VARIANTS"),
                    ("HAS_MULTI_WAREHOUSE", "HAS_MULTI_WAREHOUSE"),
                    ("HAS_HR_MODULE", "HAS_HR_MODULE"),
                    ("HAS_CASH_MODULE", "HAS_CASH_MODULE"),
                    ("HAS_GYM_MODULE", "HAS_GYM_MODULE"),
                ],
                max_length=50,
            ),
        ),
    ]
