# Generated by Django 5.0.14 on 2026-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_seed_gym_manage_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
