# Generated by Django 5.2.17 on 2026-08-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_tenant_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="terms_version_accepted",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
