# Generated by Django 5.2.17 on 2026-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_seed_bloque_a_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="cash_difference_alert_threshold",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=12),
        ),
    ]
