# Generated by Django 5.2.17 on 2026-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dos_decimales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='default_payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('YAPE', 'YAPE'), ('CREDIT_LEDGER', 'CREDIT_LEDGER'), ('BALANCE', 'BALANCE')], default='CASH', max_length=20),
        ),
    ]
