# Generated by Django 5.0.14 on 2026-07-21 21:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'promotion_products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL'), ('UNPAID', 'UNPAID')], max_length=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('VOIDED', 'VOIDED'), ('CANCELLED', 'CANCELLED')], max_length=15)),
                ('client_side_uuid', models.CharField(max_length=64, unique=True)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'SYNCED'), ('OFFLINE_PENDING', 'OFFLINE_PENDING'), ('CONFLICT', 'CONFLICT')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'db_table': 'sale_details',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('YAPE', 'YAPE'), ('CREDIT_LEDGER', 'CREDIT_LEDGER'), ('BALANCE', 'BALANCE')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale_payments',
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('total_refund_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('refund_type', models.CharField(choices=[('BALANCE', 'BALANCE'), ('CASH', 'CASH')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale_returns',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=3, max_digits=12)),
                ('restock', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'db_table': 'sale_return_details',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='inventario.warehouse')),
            ],
            options={
                'db_table': 'cash_registers',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('opening_at', models.DateTimeField()),
                ('expected_closing_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('counted_closing_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=10)),
                ('closing_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='ventas.cashregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='usuarios.user')),
            ],
            options={
                'db_table': 'cash_sessions',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('concept', models.CharField(choices=[('RETIRO', 'RETIRO'), ('PAGO_PROVEEDOR_EFECTIVO', 'PAGO_PROVEEDOR_EFECTIVO'), ('DEPOSITO_BANCO', 'DEPOSITO_BANCO'), ('AJUSTE', 'AJUSTE')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='usuarios.user')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='ventas.cashsession')),
            ],
            options={
                'db_table': 'cash_movements',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'DNI'), ('ANONIMO', 'ANONIMO')], max_length=10)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.user')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerBalanceLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_ledger', to='ventas.customer')),
            ],
            options={
                'db_table': 'customer_balance_ledger',
            },
        ),
        migrations.CreateModel(
            name='CustomerDebtLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_ledger', to='ventas.customer')),
            ],
            options={
                'db_table': 'customer_debt_ledger',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('FIXED_AMOUNT', 'FIXED_AMOUNT')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotions',
                'indexes': [models.Index(fields=['updated_at'], name='promotions_updated_92a863_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['PERCENTAGE', 'FIXED_AMOUNT'])), name='ck_promotions_type'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventario.category'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='ventas.promotion'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventario.productvariant'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ventas.cashsession'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ventas.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventario.warehouse'),
        ),
        migrations.AddField(
            model_name='customerdebtledger',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_entries', to='ventas.sale'),
        ),
        migrations.AddField(
            model_name='customerbalanceledger',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to='ventas.sale'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ventas.sale'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ventas.sale'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='ventas.sale'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='customerbalanceledger',
            name='sale_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to='ventas.salereturn'),
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_details', to='ventas.saledetail'),
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='sale_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ventas.salereturn'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='ck_cash_sessions_status'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['IN', 'OUT'])), name='ck_cash_movements_type'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='customers_updated_a69b42_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='customers_search__eb6e2d_gin'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('document_type__in', ['RUC', 'DNI', 'ANONIMO'])), name='ck_customers_document_type'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['PAID', 'PARTIAL', 'UNPAID'])), name='ck_sales_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['COMPLETED', 'VOIDED', 'CANCELLED'])), name='ck_sales_status'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('sync_status__in', ['SYNCED', 'OFFLINE_PENDING', 'CONFLICT'])), name='ck_sales_sync_status'),
        ),
        migrations.AddConstraint(
            model_name='customerdebtledger',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['DEBIT', 'CREDIT'])), name='ck_customer_debt_ledger_type'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(check=models.Q(('method__in', ['CASH', 'CARD', 'YAPE', 'CREDIT_LEDGER', 'BALANCE'])), name='ck_sale_payments_method'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(check=models.Q(('refund_type__in', ['BALANCE', 'CASH'])), name='ck_sale_returns_refund_type'),
        ),
        migrations.AddConstraint(
            model_name='customerbalanceledger',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['CREDIT', 'DEBIT'])), name='ck_customer_balance_ledger_type'),
        ),
    ]
