# Generated by Django 5.0.14 on 2026-08-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="receipt_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
