# Generated by Django 5.0.14 on 2026-08-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0002_cashmovement_reason_cashmovement_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashmovement",
            name="concept",
            field=models.CharField(
                choices=[
                    ("RETIRO", "RETIRO"),
                    ("PAGO_PROVEEDOR_EFECTIVO", "PAGO_PROVEEDOR_EFECTIVO"),
                    ("DEPOSITO_BANCO", "DEPOSITO_BANCO"),
                    ("AJUSTE", "AJUSTE"),
                    ("DEVOLUCION", "DEVOLUCION"),
                ],
                max_length=30,
            ),
        ),
    ]
