# Generated by Django 5.0.14 on 2026-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0003_cashmovement_devolucion_concept"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
