# Generated by Django 5.0.14 on 2026-08-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventario",
            "0007_alter_inventorymovement_concept_volumepricingtier_and_more",
        ),
        ("usuarios", "0004_role_deleted_at_role_deleted_by"),
        ("ventas", "0004_customer_credit_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("SENT", "SENT"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("EXPIRED", "EXPIRED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                ("subtotal", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=4, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="ventas.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="ventas.sale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="usuarios.user",
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
            },
        ),
        migrations.CreateModel(
            name="QuoteDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_id", models.IntegerField()),
                ("product_name_snapshot", models.CharField(max_length=200)),
                ("sku_snapshot", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="ventas.quote",
                    ),
                ),
            ],
            options={
                "db_table": "quote_details",
            },
        ),
        migrations.CreateModel(
            name="ProductReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("CONVERTED", "CONVERTED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="ventas.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="ventas.sale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reservations",
                        to="usuarios.user",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventario.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventario.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "product_reservations",
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="product_res_status_cf3921_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productreservation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["ACTIVE", "CONVERTED", "EXPIRED", "CANCELLED"])
                ),
                name="ck_product_reservations_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["DRAFT", "SENT", "ACCEPTED", "EXPIRED", "REJECTED"])
                ),
                name="ck_quotes_status",
            ),
        ),
    ]
