# Generated by Django 5.2.17 on 2026-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0008_inventory_movements_variant_created_idx"),
        ("usuarios", "0005_alter_permission_module_dataexport"),
        ("ventas", "0005_quote_quotedetail_productreservation_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["created_at"], name="ix_cash_movements_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(fields=["status"], name="ix_cash_sessions_status"),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["opening_at"], name="ix_cash_sessions_opening_at"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["status", "created_at"], name="ix_sales_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["payment_status"], name="ix_sales_payment_status"
            ),
        ),
    ]
