# Generated by Django 5.2.17 on 2026-09-19 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0012_product_search_vector_trigger"),
        ("usuarios", "0006_backfill_user_warehouses"),
        ("ventas", "0007_customer_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="occurred_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Las ventas existentes se hicieron online: su hora real es created_at,
        # no el momento en que corre esta migracion (default de AddField).
        migrations.RunSQL(
            sql="UPDATE sales SET occurred_at = created_at;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["status", "occurred_at"], name="ix_sales_status_occurred"
            ),
        ),
    ]
