# Generated by Django 5.2.17 on 2026-09-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_backfill_user_warehouses"),
        ("ventas", "0009_cashregister_assigned_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cashsession",
            name="ck_cash_sessions_status",
        ),
        migrations.AddField(
            model_name="cashsession",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_cash_sessions",
                to="usuarios.user",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="counted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "OPEN"),
                    ("PENDING_APPROVAL", "PENDING_APPROVAL"),
                    ("CLOSED", "CLOSED"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["OPEN", "PENDING_APPROVAL", "CLOSED"])
                ),
                name="ck_cash_sessions_status",
            ),
        ),
    ]
