# Generated by Django 5.2.17 on 2026-09-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0009_dos_decimales"),
        ("ventas", "0012_dos_decimales"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettlement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_deposited",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_settlements",
            },
        ),
        migrations.CreateModel(
            name="PaymentSettlementLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_number", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "MATCHED"),
                            ("UNMATCHED_DEPOSIT", "UNMATCHED_DEPOSIT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_settlement_lines",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="is_walk_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="credit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="credit_settled_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="card_brand",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="change_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="installments",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="is_manual",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="operation_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("VOIDED", "VOIDED"),
                    ("REFUNDED", "REFUNDED"),
                ],
                default="APPROVED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="tendered_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="voucher_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="salepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["APPROVED", "REJECTED", "VOIDED", "REFUNDED"])
                ),
                name="ck_sale_payments_status",
            ),
        ),
        migrations.AddField(
            model_name="paymentsettlement",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_settlements",
                to="usuarios.user",
            ),
        ),
        migrations.AddField(
            model_name="paymentsettlementline",
            name="matched_sale_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlement_lines",
                to="ventas.salepayment",
            ),
        ),
        migrations.AddField(
            model_name="paymentsettlementline",
            name="settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="ventas.paymentsettlement",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentsettlementline",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["MATCHED", "UNMATCHED_DEPOSIT"])),
                name="ck_payment_settlement_lines_status",
            ),
        ),
    ]
