# Generated by Django 5.0.14 on 2026-07-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('warehouse_id', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_transactions', models.IntegerField()),
                ('total_discount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('refreshed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mv_daily_sales_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('variant_id', models.IntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('min_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('refreshed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mv_low_stock_alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_code', models.CharField(choices=[('SALES_TODAY', 'SALES_TODAY'), ('LOW_STOCK', 'LOW_STOCK'), ('CASH_STATUS', 'CASH_STATUS'), ('TOP_PRODUCTS', 'TOP_PRODUCTS'), ('ATTENDANCE_TODAY', 'ATTENDANCE_TODAY')], max_length=30)),
                ('position', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboard_widgets',
            },
        ),
    ]
