# Generated by Django 5.0.14 on 2026-07-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(choices=[('SALES', 'SALES'), ('INVENTORY', 'INVENTORY'), ('PURCHASES', 'PURCHASES'), ('USERS', 'USERS'), ('REPORTS', 'REPORTS'), ('HR', 'HR'), ('CASH', 'CASH')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_system_default', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(max_length=100)),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('DAILY', 'DAILY'), ('HOURLY', 'HOURLY')], max_length=10)),
                ('salary_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='inventario.warehouse')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_TIME', 'ON_TIME'), ('LATE', 'LATE'), ('ABSENCE_JUSTIFIED', 'ABSENCE_JUSTIFIED'), ('ABSENCE_UNJUSTIFIED', 'ABSENCE_UNJUSTIFIED')], max_length=25)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='usuarios.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.warehouse')),
            ],
            options={
                'verbose_name_plural': 'employee attendance',
                'db_table': 'employee_attendance',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=4, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll', to='usuarios.employee')),
            ],
            options={
                'db_table': 'employee_payroll',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='usuarios.employee')),
            ],
            options={
                'db_table': 'employee_schedules',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='usuarios.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='usuarios.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='usuarios.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'GRANTED'), ('REVOKED', 'REVOKED')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_history', to='usuarios.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_history', to='usuarios.role')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.user')),
            ],
            options={
                'db_table': 'role_permissions_history',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='usuarios.user'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='usuarios.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='usuarios.user')),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_access', to='usuarios.user')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventario.warehouse')),
            ],
            options={
                'db_table': 'user_warehouses',
            },
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ON_TIME', 'LATE', 'ABSENCE_JUSTIFIED', 'ABSENCE_UNJUSTIFIED'])), name='ck_employee_attendance_status'),
        ),
        migrations.AddConstraint(
            model_name='employeepayroll',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'PAID'])), name='ck_employee_payroll_status'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.CheckConstraint(check=models.Q(('day_of_week__in', ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'])), name='ck_employee_schedules_day'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='uq_users_email'),
        ),
        migrations.AddConstraint(
            model_name='rolepermissionshistory',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ['GRANTED', 'REVOKED'])), name='ck_role_permissions_history_action'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('salary_type__in', ['MONTHLY', 'DAILY', 'HOURLY'])), name='ck_employees_salary_type'),
        ),
        migrations.AddConstraint(
            model_name='userwarehouse',
            constraint=models.UniqueConstraint(fields=('user', 'warehouse'), name='uq_user_warehouse'),
        ),
    ]
