# Generated by Django 5.2.17 on 2026-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_role_deleted_at_role_deleted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("SALES", "SALES"),
                    ("INVENTORY", "INVENTORY"),
                    ("PURCHASES", "PURCHASES"),
                    ("USERS", "USERS"),
                    ("REPORTS", "REPORTS"),
                    ("HR", "HR"),
                    ("CASH", "CASH"),
                    ("GYM", "GYM"),
                    ("COMPLIANCE", "COMPLIANCE"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("FULL", "FULL")], default="FULL", max_length=10
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("ZIP", "ZIP"), ("XLSX", "XLSX")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("file_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_exports",
                        to="usuarios.user",
                    ),
                ),
            ],
            options={
                "db_table": "data_exports",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope__in", ["FULL"])),
                        name="ck_data_exports_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("format__in", ["ZIP", "XLSX"])),
                        name="ck_data_exports_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "PENDING",
                                    "PROCESSING",
                                    "COMPLETED",
                                    "FAILED",
                                    "EXPIRED",
                                ],
                            )
                        ),
                        name="ck_data_exports_status",
                    ),
                ],
            },
        ),
    ]
