# Generated by Django 5.2.17 on 2026-09-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_backfill_user_warehouses"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("LOGIN", "LOGIN"),
                            ("SUPERVISOR_AUTHORIZATION", "SUPERVISOR_AUTHORIZATION"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "login_attempts",
            },
        ),
        migrations.CreateModel(
            name="SupervisorAuthorization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("permission", models.CharField(max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "supervisor_authorizations",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="max_discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_discount_percent__gte", 0), ("max_discount_percent__lte", 100)
                ),
                name="ck_roles_max_discount_percent",
            ),
        ),
        migrations.AddField(
            model_name="supervisorauthorization",
            name="authorized_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="usuarios.user",
            ),
        ),
        migrations.AddField(
            model_name="supervisorauthorization",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="usuarios.user",
            ),
        ),
    ]
