# Generated by Django 5.2.17 on 2026-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0008_seed_sales_discount_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="employeepayroll",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="employeepayroll",
            name="bonuses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="employeepayroll",
            name="deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="employeepayroll",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
