"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import sys
import dj_database_url
import sentry_sdk
from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Antes quedaba hardcodeada e ignoraba la variable de entorno -mismo problema
# que tenia ALLOWED_HOSTS. El valor "django-insecure-..." solo se usa como
# fallback de desarrollo si SECRET_KEY no esta definida en el entorno.
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-3nzrr(nes&b(0ks&5q+klr17*7px)aoj1lo38s+833)3m9-y5n"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Antes quedaba hardcodeado en True -si alguien olvidaba tocar este archivo
# antes de desplegar a produccion, DEBUG=True quedaba expuesto (stack traces
# con codigo fuente y variables de entorno visibles a cualquiera). Default
# seguro (False) si la variable no esta definida; .env de desarrollo la fija
# en True explicitamente.
DEBUG = os.getenv("DEBUG", "False") == "True"

# Antes se ignoraba la variable de entorno ALLOWED_HOSTS y quedaba en [] -en dev
# eso "funcionaba por accidente" porque Django agrega '.localhost' cuando
# DEBUG=True, pero el test runner fuerza DEBUG=False, asi que cualquier
# subdominio (ej. tenant1.localhost) fallaba con DisallowedHost solo en tests.
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost").split(",")]

# send_default_pii=False: a diferencia del snippet por defecto de Sentry, no se envian
# headers de request ni IP de usuarios -el sistema maneja datos de negocios/clientes
# sujetos a la Ley N 29733 (TRD, seccion 6.2).
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "development"),
        send_default_pii=False,
    )

# Distinto del DSN de arriba (que es para ENVIAR eventos): esto es para
# LEER eventos vía la API REST de Sentry, usado por el panel de salud por
# tenant (Especificacion de API §4.26). Si no esta configurado,
# TenantHealthService degrada con recent_errors_count=0 en vez de fallar.
SENTRY_API_TOKEN = os.getenv("SENTRY_API_TOKEN", "")
SENTRY_ORG_SLUG = os.getenv("SENTRY_ORG_SLUG", "")
SENTRY_PROJECT_SLUG = os.getenv("SENTRY_PROJECT_SLUG", "")


# Application definition

SHARED_APPS = (
    "django_tenants",  # obligatorio para el framework
    "core",  # obligatorio incluir la app donde residen los modelos Tenant y Domain
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
)

TENANT_APPS = (
    # Aplicaciones específicas para cada inquilino (tenant)
    "usuarios",
    "inventario",
    "ventas",
    "dashboard",
    "gimnasio",
)

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = "core.Tenant"
TENANT_DOMAIN_MODEL = "core.Domain"

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    # Sprint 11 (Especificacion de API §4.26): despues de TenantMainMiddleware
    # a proposito -necesita request.tenant ya resuelto.
    "core.middleware.SentryTenantTagMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # antes de CommonMiddleware (requisito de django-cors-headers)
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"), engine="django_tenants.postgresql_backend"
    )
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.PlatformStaffJWTAuthentication",
        "core.authentication.TenantValidatedJWTAuthentication",
        # Ambas conviven: cada una resuelve el user_id contra su propia
        # tabla (platform_staff / tenant.users) y no interfieren entre si.
        # Los endpoints de tenant.users llegan recien en Sprint 2.
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Fivuza API",
    "DESCRIPTION": "API para el sistema SaaS Fivuza (ERP multi-tenant)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# django-cors-headers: el frontend (puerto 5173) y el backend (puerto 8000)
# son origenes distintos incluso en desarrollo local.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")
    if origin.strip()
]
# El panel core (platform_staff) usa una VITE_API_URL fija, por eso le
# alcanza con el origen exacto de arriba. El ERP de cada tenant (Sprint 2)
# resuelve la API por window.location.hostname -su propio origen del
# navegador ES el subdominio del tenant (ej. tenant1.localhost:5173)-, asi
# que una lista fija de origenes no alcanza: se necesita un patron que
# acepte cualquier subdominio.
CORS_ALLOWED_ORIGIN_REGEXES = [
    regex.strip()
    for regex in os.getenv(
        "CORS_ALLOWED_ORIGIN_REGEXES", r"^http://([a-z0-9-]+\.)?localhost:5173$"
    ).split(",")
    if regex.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Infraestructura de djangorestframework-simplejwt (Sprint 1, Plan de Implementacion).
# Usada hoy por platform_staff (core.authentication.PlatformStaffJWTAuthentication);
# tenant.users la reutiliza a partir de Sprint 2 via TenantValidatedJWTAuthentication.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Cache de Redis (Sprint 2, Plan de Implementacion): usada por
# usuarios.services.PermissionService para no recalcular el set de permisos
# de un usuario en cada request. Backend nativo de Django (5.0+), sin
# depender de django-redis.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/0"),
    }
}

# S3 para imagenes de variante (Sprint 3, Plan de Implementacion). Las
# credenciales de AWS no se leen aqui -boto3 las toma solas de las variables
# de entorno estandar (AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY) o del rol de
# IAM de la tarea ECS en produccion (TRD §5.1); no hay que duplicarlas.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION = os.getenv("AWS_S3_REGION", "us-east-1")

# Correo transaccional (Sprint 5, hueco #2). En dev/test, EMAIL_BACKEND
# imprime el correo a consola en vez de enviarlo de verdad -no requiere
# credenciales para desarrollar ni para correr los tests. En produccion,
# Infra/QA solo necesita cambiar EMAIL_BACKEND a
# "django_ses.SESBackend" (con SES ya verificado, TRD §5.4) y las demas
# variables de entorno, sin tocar codigo.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-responder@fivuza.com")

# URL del ERP del tenant que se linkea en los correos (ej. reseteo de
# contraseña). El backend nunca sirve el frontend, asi que arma la URL a
# partir del mismo host que recibio la request (mismo patron que
# tenantApiClient.ts en el frontend, en sentido inverso) mas estas dos
# variables -distintas entre dev (puerto 5173, http) y produccion
# (sin puerto explicito, https).
FRONTEND_SCHEME = os.getenv("FRONTEND_SCHEME", "http")
FRONTEND_PORT = os.getenv("FRONTEND_PORT", "5173")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Celery (Sprint 4, Plan de Implementacion). CELERY_BROKER_URL no se leia
# antes -config.celery.py usa config_from_object("django.conf:settings",
# namespace="CELERY"), que solo encuentra ajustes con ese prefijo aqui, no
# la variable de entorno cruda del contenedor.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_TIMEZONE = TIME_ZONE
# En tests, las tareas corren en el mismo proceso en vez de encolarse en
# Redis -si no, mail.outbox (backend de correo en memoria) nunca ve el
# envio, porque ocurriria en un worker de Celery aparte que ademas no
# existe durante los tests.
CELERY_TASK_ALWAYS_EAGER = "test" in sys.argv
CELERY_BEAT_SCHEDULE = {
    # Dia 28 (nunca dia 1: hay que tener la particion del mes siguiente
    # lista ANTES de que empiece, con margen) a las 2am.
    "inventario-create-next-month-partitions": {
        "task": "inventario.tasks.create_next_month_partitions",
        "schedule": crontab(day_of_month=28, hour=2, minute=0),
    },
    "inventario-alert-low-stock": {
        "task": "inventario.tasks.alert_low_stock_variants",
        "schedule": crontab(hour=8, minute=0),
    },
    "core-check-subscription-expirations": {
        "task": "core.tasks.check_subscription_expirations",
        "schedule": crontab(hour=7, minute=0),
    },
    # Sprint 24: corre cada 5 minutos, pero cada tenant solo se refresca de
    # verdad si ya paso su propio dashboard_refresh_minutes -ver
    # DashboardRefreshService.is_due(). 5 min es un piso razonable: ningun
    # tenant configura menos que eso (Esquema Backend §9.2, "cada 15-30 min").
    "dashboard-refresh-materialized-views": {
        "task": "dashboard.tasks.refresh_materialized_views",
        "schedule": crontab(minute="*/5"),
    },
    # Sprint 28: cada 15 min es suficiente -una reserva se aparta por
    # horas/dias, no hace falta revisar mas seguido que el refresco del
    # dashboard (que si necesita ser casi en vivo).
    "ventas-expire-overdue-reservations": {
        "task": "ventas.tasks.expire_overdue_reservations",
        "schedule": crontab(minute="*/15"),
    },
    # Sprint 29: mismo criterio que la expiracion de reservas.
    "gimnasio-expire-overdue-memberships": {
        "task": "gimnasio.tasks.expire_overdue_memberships",
        "schedule": crontab(minute="*/15"),
    },
    # Una vez al dia -es un aviso informativo, no necesita la frecuencia de
    # una alerta operativa como el stock bajo.
    "gimnasio-alert-expiring-memberships": {
        "task": "gimnasio.tasks.alert_expiring_memberships",
        "schedule": crontab(hour=8, minute=30),
    },
    # Sprint 32: de madrugada, para que cada reunion comercial del dia
    # arranque con el tenant de demo en un estado limpio y conocido.
    "core-reset-demo-tenants-nightly": {
        "task": "core.tasks.reset_demo_tenants_nightly",
        "schedule": crontab(hour=3, minute=0),
    },
}

# Django Channels / WebSocket (Sprint 24, TRD §2.5): DashboardConsumer
# empuja metricas al frontend conforme ocurren ventas. Redis como channel
# layer -mismo servicio que ya usa Celery/cache, sin sumar infraestructura
# nueva al proyecto.
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://redis:6379/0")],
        },
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
