"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import dj_database_url
import sentry_sdk
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Antes quedaba hardcodeada e ignoraba la variable de entorno -mismo problema
# que tenia ALLOWED_HOSTS. El valor "django-insecure-..." solo se usa como
# fallback de desarrollo si SECRET_KEY no esta definida en el entorno.
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-3nzrr(nes&b(0ks&5q+klr17*7px)aoj1lo38s+833)3m9-y5n"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Antes se ignoraba la variable de entorno ALLOWED_HOSTS y quedaba en [] -en dev
# eso "funcionaba por accidente" porque Django agrega '.localhost' cuando
# DEBUG=True, pero el test runner fuerza DEBUG=False, asi que cualquier
# subdominio (ej. tenant1.localhost) fallaba con DisallowedHost solo en tests.
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost").split(",")]

# send_default_pii=False: a diferencia del snippet por defecto de Sentry, no se envian
# headers de request ni IP de usuarios -el sistema maneja datos de negocios/clientes
# sujetos a la Ley N 29733 (TRD, seccion 6.2).
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "development"),
        send_default_pii=False,
    )


# Application definition

SHARED_APPS = (
    "django_tenants",  # obligatorio para el framework
    "core",  # obligatorio incluir la app donde residen los modelos Tenant y Domain
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
)

TENANT_APPS = (
    # Aplicaciones específicas para cada inquilino (tenant)
    "usuarios",
    "inventario",
    "ventas",
    "dashboard",
)

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = "core.Tenant"
TENANT_DOMAIN_MODEL = "core.Domain"

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # antes de CommonMiddleware (requisito de django-cors-headers)
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"), engine="django_tenants.postgresql_backend"
    )
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.PlatformStaffJWTAuthentication",
        "core.authentication.TenantValidatedJWTAuthentication",
        # Ambas conviven: cada una resuelve el user_id contra su propia
        # tabla (platform_staff / tenant.users) y no interfieren entre si.
        # Los endpoints de tenant.users llegan recien en Sprint 2.
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Fivuza API",
    "DESCRIPTION": "API para el sistema SaaS Fivuza (ERP multi-tenant)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# django-cors-headers: el frontend (puerto 5173) y el backend (puerto 8000)
# son origenes distintos incluso en desarrollo local.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Infraestructura de djangorestframework-simplejwt (Sprint 1, Plan de Implementacion).
# Usada hoy por platform_staff (core.authentication.PlatformStaffJWTAuthentication);
# tenant.users la reutiliza a partir de Sprint 2 via TenantValidatedJWTAuthentication.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
